import rss
import unittest

test "parse rss file":
  let feed = loadRSS("./tests/test.rss")
  check(feed.title == "FeedForAll Sample Feed")
  check(feed.link == "http://www.feedforall.com/industry-solutions.htm")
  check(feed.description == "RSS is a fascinating technology. The uses for RSS are expanding daily. Take a closer look at how various industries are using the benefits of RSS in their businesses.")
  check(feed.language == "en-us")
  check(feed.copyright == "Copyright 2004 NotePage, Inc.")
  check(feed.managingEditor == "marketing@feedforall.com")
  check(feed.pubDate == "Tue, 19 Oct 2004 13:38:55 -0400")
  check(feed.webMaster == "webmaster@feedforall.com")
  check(feed.lastBuildDate == "Tue, 19 Oct 2004 13:39:14 -0400")
  check(feed.category == @["Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management", "Computers/Software/Internet/Site Management/Content Management"])
  check(feed.generator == "FeedForAll Beta1 (0.0.1.8)")
  check(feed.docs == "http://blogs.law.harvard.edu/tech/rss")
  check(feed.cloud == RSSCloud())
  check(feed.ttl == nil)
  check(feed.image == RSSImage(url: "http://www.feedforall.com/ffalogo48x48.gif", title: "FeedForAll Sample Feed", link: "http://www.feedforall.com/industry-solutions.htm", width: "48", height: "48", description: "FeedForAll Sample Feed"))
  check(feed.rating == nil)
  check(feed.textInput == RSSTextInput())
  check(feed.skipHours == nil)
  check(feed.skipDays == nil)
  check(feed.items.len == 9)

test "parse rdf file":
  let feed = loadRSS("./tests/test.rdf")
  check(feed.title == "cs updates on arXiv.org")
  check(feed.link == "http://arxiv.org/")
  check(feed.description == "Computer Science (cs) updates on the arXiv.org e-print archive")
  check(feed.language == "en-us")
  check(feed.copyright == nil)
  check(feed.managingEditor == nil)
  check(feed.pubDate == "2018-08-30T20:30:00-05:00")
  check(feed.webMaster == nil)
  check(feed.lastBuildDate == nil)
  check(feed.category == nil)
  check(feed.generator == "www-admin@arxiv.org")
  check(feed.docs == nil)
  check(feed.cloud == RSSCloud())
  check(feed.ttl == nil)
  check(feed.image == RSSImage(url: "http://arxiv.org/icons/sfx.gif", title: nil, link: nil, width: nil, height: nil, description: nil))
  check(feed.rating == nil)
  check(feed.textInput == RSSTextInput())
  check(feed.skipHours == nil)
  check(feed.skipDays == nil)
  check(feed.items.len == 185)
